# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6274768b30ff58b771c828175e3405333f6e52573705edeec9fdc4c1b1d2aedc7f03c80e0ce637a42ccf2824c26210fca7c1cf29ccca5e72004407ee9a3245d

test:
  secret_key_base: 48bea3ce9cb880120cc5768323844c84ed2011562889c8fa273d4cf8253631aceaee677410c2406ea6f6842700d525076c2202b8e14202e76eeb6578d66080ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
