#= require_tree ./adapters
#= require_tree ./mixins
#= require_tree ./models
#= require_tree ./controllers
#= require_tree ./views
#= require_directory ./lib
#= require_tree ./lib/extensions
#= require_tree ./helpers
#= require_tree ./components
#= require_tree ./templates
#= require_tree ./routes
#= require_tree ./services
#= require_tree ./initializers
#= require ./router
#= require_self
